### ISSUE TITLE
Missing translation: "loc_breed_display_name_chaos_plage_ogryn Ogryn"

### ISSUE THREAD

**Issue by ezonius** [OvenProofMars/Power_DI#8]
Typo or something? 
"plage"

![image](https://github.com/OvenProofMars/Power_DI/assets/61872098/59cf2d46-8da2-473c-a0fd-7a8993b89acd)

**Comment by OvenProofMars** [comment]
yeah, must've made an error copying stuff. Fixed it on my end, will be in the next update.

**Comment by OvenProofMars** [comment]
Current version on github has the fix. I'll upload a new version to Nexus soon as well.
